AWS_BUCKET: harnessthecrowd
AWS_ACCESS_KEY_ID: AKIAJOFY7RVQXDXGNZNQ
AWS_SECRET_ACCESS_KEY: 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
UPLOAD_STORAGE: s3
UPLOAD_PROVIDER: AWS
APP_SECRET_TOKEN: 113ef4ef33392ed203026a1401377fdb4d904f8b552bde493c3201eefcfa2e8b215bc949056b31951a76403df7778d0e314cee06eebd16160f5d846105e605c8
PAPERCLIP_HASH_SECRET: c61b3a0150cce67fb5c8d760ae17edcffb16ad2910d5a8472768f04c9fe10c40ea1c6b3140e38f599c46c023e244049c2e97f9f26525171edb8fa2233dfcf58c
PAPERCLIP_DEFAULT_PATH: /htc/:id-:hash:extension
APP_BASE_URL: http://www.harnessthecrowd.com
TWITTER_HANDLE: harnessthecrowd
MIXPANEL_ID: f71ec3d94b8bc4f3b39f8f0b01e7cd66
GA_ID: UA-42341030-1
GA_DOMAIN: harnessthecrowd.com
HEAP_ID: 3430147041
development:
  HEAP_ID: 4182550274
  GA_ID: UA-42341030-2
  GA_DOMAIN: localhost:3000
  MIXPANEL_ID: a43c7c77f9a0ba3897cb2e8b3a778c7f
  APP_BASE_URL: http://test.com
  S3_PATH_PREFIX: development_assets/
  PAPERCLIP_DEFAULT_PATH: /development_assets/:id-:hash:extension
test:
  APP_BASE_URL: http://test.com